name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH key
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.EC2_PRIVATE_KEY }}

    - name: Deploy to EC2 server
      env:
        HOST: ${{ secrets.EC2_HOST }}
        USER: ${{ secrets.EC2_USER }}
        APP_DIR: ${{ secrets.EC2_APP_DIR }}
      run: |
        ssh -o StrictHostKeyChecking=no $USER@$HOST << EOF
          set -e
          cd $APP_DIR
          git reset --hard
          git pull origin main

          npm ci
          npm run build

          pm2 stop nest-app || true
          pm2 delete nest-app || true

          pm2 stop nestjs-app || true
          pm2 delete nestjs-app || true

          pm2 start dist/main.js --name nestjs-app
          pm2 save

          pm2 list
        EOF