name: Deploy to EC2 via SSM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Send SSM Command to EC2
        id: send_command
        run: |
          INSTANCE_ID=i-0d7825c496480b14e  # Thay bằng ID EC2 của bạn
          COMMAND_ID=$(aws ssm send-command \
            --instance-ids $INSTANCE_ID \
            --document-name "AWS-RunShellScript" \
            --comment "Deploy app from GitHub Actions" \
            --parameters commands=["/home/ubuntu/deploy.sh"] \
            --query "Command.CommandId" --output text)
          echo "Command ID: $COMMAND_ID"

          # Lấy kết quả command invocation
          echo "::set-output name=command_id::$COMMAND_ID"

      - name: Wait for command completion
        run: |
          INSTANCE_ID=i-0123456789abcdef0
          COMMAND_ID=${{ steps.send_command.outputs.command_id }}

          STATUS="Pending"
          while [[ "$STATUS" == "Pending" || "$STATUS" == "InProgress" ]]; do
            STATUS=$(aws ssm list-command-invocations \
              --command-id $COMMAND_ID \
              --details \
              --query "CommandInvocations[0].Status" --output text)
            echo "Command status: $STATUS"
            sleep 5
          done

          if [[ "$STATUS" != "Success" ]]; then
            echo "Deploy command failed with status: $STATUS"
            exit 1
          fi
          echo "Deploy command succeeded!"